apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
spec:
  capacity:
    storage: 128Mi
  hostPath:
    path: /mnt/data/traefik-certs-pv
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: traefik
    name: traefik
  storageClassName: manual
