apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  - ssh:
      address: <nat-ip>
      user: root
      port: 22
    role: controller+worker
    hostname: master
    hooks:
      apply:
        before:
          - mkdir -p /mnt/data/sonar-postgres-pv
          - mkdir -p /mnt/data/jenkins-pv
          - mkdir -p /mnt/data/traefik-certs-pv
          - chmod 777 /mnt/data/*
  - ssh:
      address: <worker-0-ip>
      user: root
      port: 22
      bastion:
        address: <nat-ip>
        port: 22
        user: root
    role: worker
    hostname: worker-0
    hooks:
      apply:
        before:
          - mkdir -p /mnt/data/sonar-postgres-pv
          - mkdir -p /mnt/data/jenkins-pv
          - mkdir -p /mnt/data/traefik-certs-pv
          - chmod 777 /mnt/data/*
  - ssh:
      address: <worker-1-ip>
      user: root
      port: 22
      bastion:
        address: <nat-ip>
        user: root
        port: 22
    role: worker
    hostname: worker-1
    hooks:
      apply:
        before:
          - mkdir -p /mnt/data/sonar-postgres-pv
          - mkdir -p /mnt/data/jenkins-pv
          - mkdir -p /mnt/data/traefik-certs-pv
          - chmod 777 /mnt/data/*
  k0s:
    version: v1.21.11+k0s.0 
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      metadata:
        name: k0s
      spec:
        api:
          k0sApiPort: 9443
          port: 6443
        images:
          konnectivity:
            image: us.gcr.io/k8s-artifacts-prod/kas-network-proxy/proxy-agent
            version: v0.0.25
          metricsserver:
            image: gcr.io/k8s-staging-metrics-server/metrics-server
            version: v0.3.7
          kubeproxy:
            image: k8s.gcr.io/kube-proxy
            version: v1.21.11
          coredns:
            image: docker.io/coredns/coredns
            version: 1.7.0
          calico:
            cni:
              image: docker.io/calico/cni
              version: v3.18.1
            node:
              image: docker.io/calico/node
              version: v3.18.1
            kubecontrollers:
              image: docker.io/calico/kube-controllers
              version: v3.18.1
          kuberouter:
            cni:
              image: docker.io/cloudnativelabs/kube-router
              version: v1.2.1
            cniInstaller:
              image: quay.io/k0sproject/cni-node
              version: 0.1.0
        installConfig:
          users:
            etcdUser: etcd
            kineUser: kube-apiserver
            konnectivityUser: konnectivity-server
            kubeAPIserverUser: kube-apiserver
            kubeSchedulerUser: kube-scheduler
        konnectivity:
          adminPort: 8133
          agentPort: 8132
        network:
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
          provider: calico
          calico: 
            mode: vxlan
            vxlanPort: 4789
            vxlanVNI: 4096
            mtu: 0
            wireguard: false
            flexVolumeDriverPath: /usr/libexec/k0s/kubelet-plugins/volume/exec/nodeagent~uds
            withWindowsNodes: false
            overlay: Always
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        storage:
          type: etcd
        telemetry:
          enabled: true
