apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
spec:
  capacity:
    storage: 8Gi
  hostPath:
    path: /mnt/data/jenkins-pv
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: jenkins
    name: jenkins
  storageClassName: manual
